---
sensors:
  - module: avista_sensors.impl.random_processor
    cls: RandomProcessor
    name: Test
    parameters:
      - key: x
        value: 1
      - key: y
        value: 2
  - module: avista_sensors.impl.random_processor
    cls: RandomProcessor
    name: Test2
    parameters:
      - key: x
        value: 3
      - key: y
        value: 4